
# *** YOUR CODE HERE ***
# Lanzar un contenedor de esta forma:
# - Modo detached a partir de la imagen ualmtorres/books-app:v0
# - Mapeando el puerto 80 con el puerto 80 del contenedor
# - Configurando esta variable de entorno
#   - BOOK_API_HOST=<direccion-ip-fija-instancia-API>  
# **********************

services:
  web:
    image: ualmtorres/books-app:v0
    environment:
      - BOOK_API_HOST=10.0.0.3
    ports:
      - 80:80